---
- name: Make sure Elasticsearch service is running
  service: name=elasticsearch enabled=yes state=started

- name: Wait for cluster health to return to green
  uri: url=http://localhost:{{ es_http_port }}/_cluster/health method=GET
  register: response
  until: not response.failed and response.json.status == 'green'
  retries: 50
  delay: 30

